import {
  CYCLE_LENGTH_BLOCKS,
  MAX_GREEN_BLOCKS,
  MIN_GREEN_BLOCKS,
  ROUND_LENGTH_BLOCKS,
  TRACK_LENGTH,
  blocksUntilLightChange,
  greenBlocksInCycle,
  lightAt,
  lightRuns,
  nextLightChangeAfter,
  stepWindow,
} from "./light.ts";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

/**
 * Differential test: the TypeScript light schedule against the committed fixture that was
 * generated by the Solidity implementation.
 *
 * `packages/foundry/test/LightFixtureParity.t.sol` checks the Solidity side against the SAME file.
 * Solidity == fixture and TypeScript == fixture, therefore Solidity == TypeScript — without either
 * implementation ever importing the other, and with each checked in its own native runner.
 *
 * This matters more than any other test here. Clients compute the light locally to keep RPC reads
 * near zero, so a one-block disagreement would show a player a green light while the chain saw red
 * and eliminated them. The game would look broken and rigged at the same time.
 *
 * Run with: yarn test:light
 */

const here = dirname(fileURLToPath(import.meta.url));
const fixturePath = join(here, "../../../foundry/test/fixtures/light-fixture.json");
const vectorsPath = join(here, "../../../foundry/test/fixtures/lightAt.vectors.json");

type Series = {
  roundId: number;
  startBlock: number;
  firstBlock: number;
  pattern: string;
  greenLengths: number[];
  changeBlocks: [number, number][];
};

type Fixture = {
  cycleLengthBlocks: number;
  minGreenBlocks: number;
  maxGreenBlocks: number;
  trackLength: number;
  roundLengthBlocks: number;
  seriesCount: number;
  seriesLength: number;
  greenLengthCount: number;
  changeBlockCount: number;
  series: Series[];
};

const fixture: Fixture = JSON.parse(readFileSync(fixturePath, "utf8"));

/**
 * Vectors from a THIRD, independent implementation.
 *
 * The `light-fixture.json` checks above are generated from the Solidity, so they prove the
 * TypeScript port matches the contract — but they cannot catch a mistake the two share. If both
 * sides encoded the keccak input the same wrong way (packed instead of `abi.encode`, or the wrong
 * argument widths, or the arguments swapped), the two would agree perfectly and both would be
 * wrong, and players would be shown a light the chain does not enforce.
 *
 * These vectors were written separately, from the specification rather than from this code, so
 * agreement across all three implementations is what actually confirms the encoding.
 * `lightAt.vectors.generator.mjs` sits beside them so they can be regenerated and audited.
 *
 * WHAT THEY DO AND DO NOT CATCH, checked by deliberately mis-encoding and counting mismatches
 * across all 36 vectors:
 *   - `encodePacked` instead of `abi.encode`  -> 36/36 caught
 *   - arguments swapped                        -> 30/36 caught
 *   - `roundId` widened to `uint256`           ->  0/36 caught, and rightly so: `abi.encode`
 *     left-pads a `uint32` and a `uint256` to the same 32-byte word, so the encodings are
 *     byte-identical. Not a gap in the vectors, a property of ABI encoding.
 */
type Vector = {
  roundId: number;
  startBlock: string;
  block: string;
  green: boolean;
  greenInCycle: string;
};

const vectors: Vector[] = JSON.parse(readFileSync(vectorsPath, "utf8"));

test("lightAt matches an independent third implementation", () => {
  assert.ok(vectors.length >= 36, `expected at least 36 vectors, got ${vectors.length}`);

  for (const vector of vectors) {
    const startBlock = BigInt(vector.startBlock);
    const blockNumber = BigInt(vector.block);

    assert.equal(
      lightAt(vector.roundId, startBlock, blockNumber),
      vector.green,
      `round ${vector.roundId} start ${vector.startBlock} block ${vector.block}`,
    );

    assert.equal(
      greenBlocksInCycle(vector.roundId, (blockNumber - startBlock) / CYCLE_LENGTH_BLOCKS),
      BigInt(vector.greenInCycle),
      `greenInCycle for round ${vector.roundId} block ${vector.block}`,
    );
  }
});

test("independent vectors cover several rounds and a realistic block height", () => {
  // A vector set that only exercised round 1 at block 1000 would pass trivially without testing
  // the encoding at any width that matters.
  const rounds = new Set(vectors.map(v => v.roundId));
  assert.ok(rounds.size >= 3, `expected at least 3 distinct rounds, got ${rounds.size}`);
  assert.ok(
    vectors.some(v => BigInt(v.block) > 50_000_000n),
    "expected a vector at a realistic live block height",
  );
  assert.ok(
    vectors.some(v => v.startBlock === "0"),
    "expected a vector anchored at block 0",
  );
  // And they must actually disagree with each other, or they prove nothing.
  assert.ok(
    vectors.some(v => v.green) && vectors.some(v => !v.green),
    "vectors must contain both green and red blocks",
  );
});

test("constants match the Solidity contract", () => {
  // Checked first: if these drift, every pattern below is meaningless and the failure should name
  // the real cause rather than print a wall of mismatched blocks.
  assert.equal(CYCLE_LENGTH_BLOCKS, BigInt(fixture.cycleLengthBlocks));
  assert.equal(MIN_GREEN_BLOCKS, BigInt(fixture.minGreenBlocks));
  assert.equal(MAX_GREEN_BLOCKS, BigInt(fixture.maxGreenBlocks));
  assert.equal(TRACK_LENGTH, fixture.trackLength);
  assert.equal(ROUND_LENGTH_BLOCKS, BigInt(fixture.roundLengthBlocks));
});

test("fixture is actually populated", () => {
  // Guards against the fixture being regenerated into something empty and this whole file then
  // passing while verifying nothing.
  assert.equal(fixture.series.length, fixture.seriesCount);
  assert.ok(fixture.seriesCount >= 6, "expected at least 6 series");
  assert.ok(fixture.seriesLength >= 600, "expected at least 600 blocks per series");
  for (const s of fixture.series) {
    assert.equal(s.pattern.length, fixture.seriesLength);
    assert.equal(s.greenLengths.length, fixture.greenLengthCount);
    assert.equal(s.changeBlocks.length, fixture.changeBlockCount);
  }
});

test("lightAt matches Solidity for every block in the fixture", () => {
  let checked = 0;

  for (const s of fixture.series) {
    const startBlock = BigInt(s.startBlock);
    const firstBlock = BigInt(s.firstBlock);

    for (let i = 0; i < s.pattern.length; i++) {
      const expected = s.pattern[i] === "G";
      const blockNumber = firstBlock + BigInt(i);
      const actual = lightAt(s.roundId, startBlock, blockNumber);

      assert.equal(
        actual,
        expected,
        `round ${s.roundId} start ${s.startBlock} block ${blockNumber}: expected ${
          expected ? "GREEN" : "RED"
        }, got ${actual ? "GREEN" : "RED"}`,
      );
      checked++;
    }
  }

  assert.ok(checked >= 3600, `expected to check at least 3600 blocks, checked ${checked}`);
});

test("greenBlocksInCycle matches Solidity", () => {
  for (const s of fixture.series) {
    for (let c = 0; c < s.greenLengths.length; c++) {
      assert.equal(
        greenBlocksInCycle(s.roundId, BigInt(c)),
        BigInt(s.greenLengths[c]),
        `round ${s.roundId} cycle ${c}`,
      );
    }
  }
});

test("nextLightChangeAfter matches Solidity", () => {
  for (const s of fixture.series) {
    for (const [from, expected] of s.changeBlocks) {
      assert.equal(
        nextLightChangeAfter(s.roundId, BigInt(s.startBlock), BigInt(from)),
        BigInt(expected),
        `round ${s.roundId} from block ${from}`,
      );
    }
  }
});

test("the fixture exercises the awkward inputs, not just tidy ones", () => {
  const roundIds = fixture.series.map(s => s.roundId);
  assert.ok(roundIds.includes(0), "round id 0 should be covered");
  assert.ok(roundIds.includes(0xffffffff), "max uint32 round id should be covered");
  assert.ok(
    fixture.series.some(s => s.startBlock === 0),
    "start block 0 should be covered",
  );
  assert.ok(
    fixture.series.some(s => s.firstBlock < s.startBlock),
    "blocks before the round start should be covered",
  );
});

test("blocks before the round starts read as green", () => {
  assert.equal(lightAt(1, 1000n, 999n), true);
  assert.equal(lightAt(1, 1000n, 0n), true);
  assert.equal(nextLightChangeAfter(1, 1000n, 500n), 1000n);
});

test("green length is always in range and always leaves at least one red block", () => {
  for (let roundId = 0; roundId < 40; roundId++) {
    for (let cycle = 0n; cycle < 60n; cycle++) {
      const green = greenBlocksInCycle(roundId, cycle);
      assert.ok(green >= MIN_GREEN_BLOCKS, `green ${green} below min`);
      assert.ok(green <= MAX_GREEN_BLOCKS, `green ${green} above max`);
      assert.ok(green < CYCLE_LENGTH_BLOCKS, "a cycle must always contain a red block");
    }
  }
});

test("nextLightChangeAfter always lands on a genuine colour flip", () => {
  const startBlock = 1000n;

  for (let i = 0n; i < 2000n; i++) {
    const b = startBlock + i;
    const here = lightAt(3, startBlock, b);
    const change = nextLightChangeAfter(3, startBlock, b);

    assert.ok(change > b, "the change must be strictly in the future");
    assert.notEqual(lightAt(3, startBlock, change), here, "the colour must differ at the change");

    for (let mid = b + 1n; mid < change; mid++) {
      assert.equal(lightAt(3, startBlock, mid), here, "colour must be stable until the change");
    }
  }
});

test("blocksUntilLightChange counts the current block as one", () => {
  const startBlock = 1000n;
  // Cycle 0 of round 1 is 12 green blocks (from the fixture), so at the very first block of the
  // round the current colour has all 12 of them left.
  assert.equal(greenBlocksInCycle(1, 0n), 12n);
  assert.equal(blocksUntilLightChange(1, startBlock, 1000n), 12n);
  assert.equal(blocksUntilLightChange(1, startBlock, 1011n), 1n);
  assert.equal(lightAt(1, startBlock, 1011n), true);
  assert.equal(lightAt(1, startBlock, 1012n), false);
});

test("stepWindow describes exactly the blocks a step could land in", () => {
  const startBlock = 1000n;

  // A SAFE step from block 1000 can only land in 1001, which is green.
  const safe = stepWindow(1, startBlock, 1000n, 1001n);
  assert.equal(safe.blocks.length, 1);
  assert.equal(safe.blocks[0].blockNumber, 1001n);
  assert.equal(safe.allGreen, true);
  assert.equal(safe.redCount, 0);

  // A DASH from block 1000 covers 1001..1004, all still inside the 12 green blocks.
  const dash = stepWindow(1, startBlock, 1000n, 1004n);
  assert.equal(dash.blocks.length, 4);
  assert.equal(dash.allGreen, true);

  // A DASH taken too late straddles the light change at 1012 and is genuinely risky.
  const risky = stepWindow(1, startBlock, 1010n, 1014n);
  assert.equal(risky.blocks.length, 4); // 1011, 1012, 1013, 1014
  assert.equal(risky.allGreen, false);
  assert.equal(risky.redCount, 3); // 1012, 1013, 1014 are red
  assert.equal(risky.blocks[0].isGreen, true);

  // A SAFE step at the same moment is still guaranteed, which is the whole point of the choice.
  const safeLate = stepWindow(1, startBlock, 1010n, 1011n);
  assert.equal(safeLate.allGreen, true);

  // One block later, even SAFE is fatal — and the player can see that before deciding.
  const safeTooLate = stepWindow(1, startBlock, 1011n, 1012n);
  assert.equal(safeTooLate.allGreen, false);
  assert.equal(safeTooLate.redCount, 1);
});

test("stepWindow reports an empty window as not-all-green rather than trivially safe", () => {
  // maxBlock in the past: nothing can land, so this must not read as a guaranteed step.
  const empty = stepWindow(1, 1000n, 1000n, 999n);
  assert.equal(empty.blocks.length, 0);
  assert.equal(empty.allGreen, false);
});

test("lightRuns tiles the requested span exactly once with alternating colours", () => {
  const startBlock = 1000n;
  const from = 1000n;
  const to = 1400n;
  const runs = lightRuns(1, startBlock, from, to);

  assert.ok(runs.length > 1);
  assert.equal(runs[0].startBlock, from);
  assert.equal(runs[runs.length - 1].endBlock, to);

  for (let i = 0; i < runs.length; i++) {
    assert.ok(runs[i].endBlock >= runs[i].startBlock, "runs must be non-empty");
    if (i > 0) {
      assert.equal(runs[i].startBlock, runs[i - 1].endBlock + 1n, "runs must be contiguous");
      assert.notEqual(runs[i].isGreen, runs[i - 1].isGreen, "adjacent runs must differ in colour");
    }
    // Every block in the run really is the colour the run claims.
    for (let b = runs[i].startBlock; b <= runs[i].endBlock; b++) {
      assert.equal(lightAt(1, startBlock, b), runs[i].isGreen);
    }
  }
});

test("lightRuns handles degenerate spans", () => {
  assert.deepEqual(lightRuns(1, 1000n, 1200n, 1199n), []);
  const single = lightRuns(1, 1000n, 1000n, 1000n);
  assert.equal(single.length, 1);
  assert.equal(single[0].startBlock, 1000n);
  assert.equal(single[0].endBlock, 1000n);
});

test("the schedule really does differ between rounds", () => {
  // Not a cryptographic claim — just confirms roundId actually feeds the hash, so a player cannot
  // memorise one round's schedule and replay it in the next.
  let differences = 0;
  for (let cycle = 0n; cycle < 100n; cycle++) {
    if (greenBlocksInCycle(1, cycle) !== greenBlocksInCycle(2, cycle)) differences++;
  }
  assert.ok(differences > 50, `expected round id to change the schedule, got ${differences}/100`);
});

test("measured green share over 20,000 blocks stays near half", () => {
  const startBlock = 1000n;
  const samples = 20000;
  let green = 0;
  let minRun = Infinity;
  let maxRun = 0;
  let run = 0;

  for (let i = 0; i < samples; i++) {
    if (lightAt(1, startBlock, startBlock + BigInt(i))) {
      green++;
      run++;
    } else if (run > 0) {
      minRun = Math.min(minRun, run);
      maxRun = Math.max(maxRun, run);
      run = 0;
    }
  }

  const share = (green / samples) * 100;
  // Reproduces the Solidity-side measurement in test_Light_MeasuredGreenShareAndRunLengths.
  assert.ok(share > 45 && share < 60, `green share ${share.toFixed(1)}% out of range`);
  assert.equal(minRun, Number(MIN_GREEN_BLOCKS));
  assert.equal(maxRun, Number(MAX_GREEN_BLOCKS));
  console.log(`  measured green share: ${share.toFixed(1)}%, runs ${minRun}-${maxRun} blocks`);
});
